global using System.ComponentModel.DataAnnotations;
global using System.ComponentModel.DataAnnotations.Schema;
global using CompanyStructureApi.Models;
global using CompanyStructureApi.Data;
global using CompanyStructureApi.DTOs.Companies;
global using CompanyStructureApi.DTOs.Employees;
global using CompanyStructureApi.DTOs.Divisions;
global using CompanyStructureApi.DTOs.Projects;
global using CompanyStructureApi.DTOs.Departments;